# Generated by Django 6.1.1 on 2026-10-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('legal_practitioner', 'Lawyer'), ('judicial_officer', 'Judge'), ('court_registry', 'Registry'), ('litigant', 'Litigant')], max_length=32),
        ),
    ]
