# Generated by Django 6.1.1 on 2026-10-08 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_notification_email_delivered_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courtcase',
            name='court_division',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='filing',
            name='fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='filing',
            name='payment_proof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_proofs', to='cases.casedocument'),
        ),
        migrations.AddField(
            model_name='filing',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='filing',
            name='payment_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filing',
            name='payment_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_filing_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filing',
            name='payment_status',
            field=models.CharField(choices=[('pending_review', 'Pending review'), ('verified', 'Verified')], default='pending_review', max_length=20),
        ),
    ]
